global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['gateway:8080']

  - job_name: farmer-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['farmer-service:8081']

  - job_name: admin-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['admin-service:8082']

  - job_name: claims-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['claims-service:8083']

  - job_name: state-router-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['state-router-service:8084']

  - job_name: ml-service
    metrics_path: /metrics
    static_configs:
      - targets: ['ml-service:8000']
