server:
  port: 8086
spring:
  application:
    name: kyc-service
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
app:
  dev-mode: ${DEV_MODE:true}
protean:
  api:
    base-url: https://api.risewithprotean.io
    client-id: ${PROTEAN_CLIENT_ID:dummy_id}
    client-secret: ${PROTEAN_CLIENT_SECRET:dummy_secret}
