import { Router, type IRouter } from "express";
import healthRouter from "./health";
import farmerAuthRouter from "./farmer-auth";
import farmerRouter from "./farmer";
import adminAuthRouter from "./admin-auth";
import adminRouter from "./admin";
import claimsRouter from "./claims";
import locationRouter from "./location";
import cscRouter from "./csc";
import inspectorRouter from "./inspector";
import insurerRouter from "./insurer";
import { systemRouter } from "./system";
import { evidenceRouter } from "./evidence";
import satelliteRouter from "./satellite";
import carbonRouter from "./carbon";
import authRouter from "./auth";
import analyticsRouter from "./analytics";
import landRouter from "./land";
import udlrnRouter from "./udlrn";
import scoringRouter from "./scoring";
import fieldVisitsRouter from "./field-visits";
import farmersAdminRouter from "./farmers-admin";
import auditRouter from "./audit";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/v1/auth", authRouter);
router.use("/v1/farmer", farmerAuthRouter);
router.use("/v1/farmer", farmerRouter);
router.use("/v1/admin", adminAuthRouter);
router.use("/v1/admin", adminRouter);
router.use("/v1/claims", claimsRouter);
router.use("/v1/location", locationRouter);
router.use("/v1/csc", cscRouter);
router.use("/v1/inspector", inspectorRouter);
router.use("/v1/insurer", insurerRouter);
router.use("/system", systemRouter);
router.use("/v1/evidence", evidenceRouter);
router.use("/v1/satellite", satelliteRouter);
router.use("/v1/carbon", carbonRouter);
router.use("/v1/analytics", analyticsRouter);
router.use("/v1/land", landRouter);
router.use("/v1/udlrn", udlrnRouter);
router.use("/v1/scoring", scoringRouter);
router.use("/v1/field-visits", fieldVisitsRouter);
router.use("/v1/farmers", farmersAdminRouter);
router.use("/v1/audit", auditRouter);

export default router;
